# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'customer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Customer(object):
    def setupUi(self, Customer):
        Customer.setObjectName("Customer")
        Customer.resize(474, 419)
        Customer.setMaximumSize(QtCore.QSize(520, 475))
        Customer.setWindowTitle("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/favicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Customer.setWindowIcon(icon)
        Customer.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(Customer)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_customer = QtWidgets.QWidget(Customer)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(False)
        font.setWeight(50)
        self.widget_customer.setFont(font)
        self.widget_customer.setObjectName("widget_customer")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_customer)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_add_customer = QtWidgets.QLabel(self.widget_customer)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_add_customer.setFont(font)
        self.label_add_customer.setStyleSheet("background-color:transparent;")
        self.label_add_customer.setObjectName("label_add_customer")
        self.verticalLayout_6.addWidget(self.label_add_customer)
        self.label_customer_id = QtWidgets.QLabel(self.widget_customer)
        self.label_customer_id.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(3)
        font.setBold(False)
        font.setWeight(50)
        self.label_customer_id.setFont(font)
        self.label_customer_id.setStyleSheet("color:transparent;")
        self.label_customer_id.setText("")
        self.label_customer_id.setObjectName("label_customer_id")
        self.verticalLayout_6.addWidget(self.label_customer_id)
        self.line = QtWidgets.QFrame(self.widget_customer)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_name = QtWidgets.QLabel(self.widget_customer)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_name.setFont(font)
        self.label_name.setStyleSheet("background-color:transparent;")
        self.label_name.setObjectName("label_name")
        self.verticalLayout.addWidget(self.label_name)
        self.input_name = QtWidgets.QLineEdit(self.widget_customer)
        self.input_name.setMinimumSize(QtCore.QSize(200, 0))
        self.input_name.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.input_name.setFont(font)
        self.input_name.setStyleSheet("border:1px solid #006EFF;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:6px;\n"
"height:25px\n"
"")
        self.input_name.setMaxLength(100)
        self.input_name.setPlaceholderText("")
        self.input_name.setClearButtonEnabled(True)
        self.input_name.setObjectName("input_name")
        self.verticalLayout.addWidget(self.input_name)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_phone_1 = QtWidgets.QLabel(self.widget_customer)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_phone_1.setFont(font)
        self.label_phone_1.setStyleSheet("background-color:transparent;")
        self.label_phone_1.setObjectName("label_phone_1")
        self.verticalLayout_3.addWidget(self.label_phone_1)
        self.input_phone_1 = QtWidgets.QLineEdit(self.widget_customer)
        self.input_phone_1.setMinimumSize(QtCore.QSize(200, 0))
        self.input_phone_1.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.input_phone_1.setFont(font)
        self.input_phone_1.setStyleSheet("border:1px solid #006EFF;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:6px;\n"
"height:25px\n"
"")
        self.input_phone_1.setMaxLength(12)
        self.input_phone_1.setPlaceholderText("")
        self.input_phone_1.setClearButtonEnabled(True)
        self.input_phone_1.setObjectName("input_phone_1")
        self.verticalLayout_3.addWidget(self.input_phone_1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_phone_2 = QtWidgets.QLabel(self.widget_customer)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_phone_2.setFont(font)
        self.label_phone_2.setStyleSheet("background-color:transparent;")
        self.label_phone_2.setObjectName("label_phone_2")
        self.verticalLayout_4.addWidget(self.label_phone_2)
        self.input_phone_2 = QtWidgets.QLineEdit(self.widget_customer)
        self.input_phone_2.setMinimumSize(QtCore.QSize(200, 0))
        self.input_phone_2.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.input_phone_2.setFont(font)
        self.input_phone_2.setStyleSheet("border:1px solid #006EFF;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:6px;\n"
"height:25px\n"
"")
        self.input_phone_2.setText("")
        self.input_phone_2.setMaxLength(12)
        self.input_phone_2.setPlaceholderText("")
        self.input_phone_2.setClearButtonEnabled(True)
        self.input_phone_2.setObjectName("input_phone_2")
        self.verticalLayout_4.addWidget(self.input_phone_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_address = QtWidgets.QLabel(self.widget_customer)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_address.setFont(font)
        self.label_address.setStyleSheet("background-color:transparent;")
        self.label_address.setObjectName("label_address")
        self.verticalLayout_5.addWidget(self.label_address)
        self.input_address = QtWidgets.QLineEdit(self.widget_customer)
        self.input_address.setMinimumSize(QtCore.QSize(200, 0))
        self.input_address.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.input_address.setFont(font)
        self.input_address.setStyleSheet("border:1px solid #006EFF;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:6px;\n"
"height:25px\n"
"")
        self.input_address.setMaxLength(55)
        self.input_address.setPlaceholderText("")
        self.input_address.setClearButtonEnabled(True)
        self.input_address.setObjectName("input_address")
        self.verticalLayout_5.addWidget(self.input_address)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem3)
        self.checkBox_level_customer = QtWidgets.QCheckBox(self.widget_customer)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_level_customer.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/crown.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_level_customer.setIcon(icon1)
        self.checkBox_level_customer.setIconSize(QtCore.QSize(18, 18))
        self.checkBox_level_customer.setTristate(False)
        self.checkBox_level_customer.setObjectName("checkBox_level_customer")
        self.verticalLayout_6.addWidget(self.checkBox_level_customer)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_add = QtWidgets.QPushButton(self.widget_customer)
        self.button_add.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.button_add.setFont(font)
        self.button_add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_add.setStyleSheet("QPushButton{\n"
"    color:#006EFF;\n"
"    height:30px;\n"
"    padding:0 5px 0 5px;\n"
"    border:1px solid #006EFF;\n"
"    border-radius:8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(216, 216, 216); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: white; \n"
"}")
        self.button_add.setIconSize(QtCore.QSize(20, 20))
        self.button_add.setCheckable(False)
        self.button_add.setAutoExclusive(False)
        self.button_add.setObjectName("button_add")
        self.horizontalLayout.addWidget(self.button_add)
        self.button_add_and_create = QtWidgets.QPushButton(self.widget_customer)
        self.button_add_and_create.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.button_add_and_create.setFont(font)
        self.button_add_and_create.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_add_and_create.setStyleSheet("QPushButton{\n"
"    color:#006EFF;\n"
"    height:30px;\n"
"    padding:0 5px 0 5px;\n"
"    border:1px solid #006EFF;\n"
"    border-radius:8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(216, 216, 216); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: white; \n"
"}")
        self.button_add_and_create.setIconSize(QtCore.QSize(20, 20))
        self.button_add_and_create.setCheckable(False)
        self.button_add_and_create.setAutoExclusive(False)
        self.button_add_and_create.setObjectName("button_add_and_create")
        self.horizontalLayout.addWidget(self.button_add_and_create)
        self.button_cancel = QtWidgets.QPushButton(self.widget_customer)
        self.button_cancel.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.button_cancel.setFont(font)
        self.button_cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_cancel.setStyleSheet("QPushButton{\n"
"    color:rgb(255, 53, 53);\n"
"    height:30px;\n"
"    padding:0 5px 0 5px;\n"
"    border:1px solid rgb(255, 53, 53);\n"
"    border-radius:8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(216, 216, 216); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: white; \n"
"}")
        self.button_cancel.setIconSize(QtCore.QSize(20, 20))
        self.button_cancel.setCheckable(False)
        self.button_cancel.setAutoExclusive(False)
        self.button_cancel.setObjectName("button_cancel")
        self.horizontalLayout.addWidget(self.button_cancel)
        spacerItem5 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.button_delete = QtWidgets.QPushButton(self.widget_customer)
        self.button_delete.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.button_delete.setFont(font)
        self.button_delete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_delete.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_delete.setStyleSheet("QPushButton{\n"
"    color:rgb(255, 53, 53);\n"
"    height:30px;\n"
"    padding:0 5px 0 5px;\n"
"    border:1px solid rgb(255, 53, 53);\n"
"    border-radius:8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(216, 216, 216); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: white; \n"
"}")
        self.button_delete.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_delete.setIcon(icon2)
        self.button_delete.setIconSize(QtCore.QSize(20, 20))
        self.button_delete.setCheckable(False)
        self.button_delete.setAutoExclusive(False)
        self.button_delete.setObjectName("button_delete")
        self.horizontalLayout.addWidget(self.button_delete)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_7.addWidget(self.widget_customer)

        self.retranslateUi(Customer)
        QtCore.QMetaObject.connectSlotsByName(Customer)

    def retranslateUi(self, Customer):
        _translate = QtCore.QCoreApplication.translate
        self.label_add_customer.setText(_translate("Customer", "Müştəri əlavə et"))
        self.label_name.setText(_translate("Customer", "Ad - Soyad*"))
        self.input_name.setToolTip(_translate("Customer", "Müştəri adı və soyadı"))
        self.label_phone_1.setText(_translate("Customer", "Telefon 1*"))
        self.input_phone_1.setToolTip(_translate("Customer", "Telefon nömrəsi"))
        self.label_phone_2.setText(_translate("Customer", "Telefon 2"))
        self.input_phone_2.setToolTip(_translate("Customer", "Telefon nömrəsi"))
        self.label_address.setText(_translate("Customer", "Ünvan*"))
        self.input_address.setToolTip(_translate("Customer", "Ünvan"))
        self.checkBox_level_customer.setText(_translate("Customer", "Loyal"))
        self.button_add.setToolTip(_translate("Customer", "Enter"))
        self.button_add.setText(_translate("Customer", "Təsdiqlə"))
        self.button_add.setShortcut(_translate("Customer", "Return"))
        self.button_add_and_create.setToolTip(_translate("Customer", "Yarat və Əlavə et - Ctrl+Enter"))
        self.button_add_and_create.setText(_translate("Customer", "Əlavə et"))
        self.button_add_and_create.setShortcut(_translate("Customer", "Ctrl+Return"))
        self.button_cancel.setToolTip(_translate("Customer", "Esc"))
        self.button_cancel.setText(_translate("Customer", "Ləğv et"))
        self.button_cancel.setShortcut(_translate("Customer", "Esc"))
        self.button_delete.setToolTip(_translate("Customer", "Müştərini sil - Ctrl+Del"))
        self.button_delete.setShortcut(_translate("Customer", "Ctrl+Del"))
import resources_rc
