# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'price.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Price(object):
    def setupUi(self, Price):
        Price.setObjectName("Price")
        Price.resize(350, 250)
        Price.setMinimumSize(QtCore.QSize(350, 250))
        Price.setMaximumSize(QtCore.QSize(350, 250))
        Price.setWindowTitle("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/favicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Price.setWindowIcon(icon)
        Price.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Price)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_price = QtWidgets.QWidget(Price)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(False)
        font.setWeight(50)
        self.widget_price.setFont(font)
        self.widget_price.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget_price.setObjectName("widget_price")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_price)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_product = QtWidgets.QLabel(self.widget_price)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_product.setFont(font)
        self.label_product.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_product.setStyleSheet("background-color:transparent;")
        self.label_product.setText("")
        self.label_product.setWordWrap(True)
        self.label_product.setObjectName("label_product")
        self.verticalLayout_3.addWidget(self.label_product)
        self.label_id = QtWidgets.QLabel(self.widget_price)
        self.label_id.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(3)
        font.setBold(False)
        font.setWeight(50)
        self.label_id.setFont(font)
        self.label_id.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_id.setStyleSheet("color:transparent;")
        self.label_id.setText("")
        self.label_id.setObjectName("label_id")
        self.verticalLayout_3.addWidget(self.label_id)
        self.line = QtWidgets.QFrame(self.widget_price)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setFocusPolicy(QtCore.Qt.NoFocus)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.label_stock_quantity = QtWidgets.QLabel(self.widget_price)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_stock_quantity.setFont(font)
        self.label_stock_quantity.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_stock_quantity.setStyleSheet("background-color:transparent;")
        self.label_stock_quantity.setWordWrap(True)
        self.label_stock_quantity.setObjectName("label_stock_quantity")
        self.verticalLayout_3.addWidget(self.label_stock_quantity)
        self.line_2 = QtWidgets.QFrame(self.widget_price)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(False)
        font.setWeight(50)
        self.line_2.setFont(font)
        self.line_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(14)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_quantity = QtWidgets.QLabel(self.widget_price)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_quantity.setFont(font)
        self.label_quantity.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_quantity.setStyleSheet("background-color:transparent;")
        self.label_quantity.setObjectName("label_quantity")
        self.verticalLayout.addWidget(self.label_quantity)
        self.input_quantity = QtWidgets.QLineEdit(self.widget_price)
        self.input_quantity.setMinimumSize(QtCore.QSize(0, 0))
        self.input_quantity.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.input_quantity.setFont(font)
        self.input_quantity.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.input_quantity.setAutoFillBackground(False)
        self.input_quantity.setStyleSheet("border:1px solid #006EFF;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:6px;\n"
"height:25px;\n"
"")
        self.input_quantity.setText("")
        self.input_quantity.setMaxLength(10)
        self.input_quantity.setClearButtonEnabled(True)
        self.input_quantity.setObjectName("input_quantity")
        self.verticalLayout.addWidget(self.input_quantity)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_price = QtWidgets.QLabel(self.widget_price)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_price.setFont(font)
        self.label_price.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_price.setStyleSheet("background-color:transparent;")
        self.label_price.setObjectName("label_price")
        self.verticalLayout_2.addWidget(self.label_price)
        self.input_price = QtWidgets.QLineEdit(self.widget_price)
        self.input_price.setMinimumSize(QtCore.QSize(0, 0))
        self.input_price.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.input_price.setFont(font)
        self.input_price.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.input_price.setStyleSheet("border:1px solid #006EFF;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:6px;\n"
"height:25px\n"
"")
        self.input_price.setText("")
        self.input_price.setMaxLength(10)
        self.input_price.setClearButtonEnabled(True)
        self.input_price.setObjectName("input_price")
        self.verticalLayout_2.addWidget(self.input_price)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_add = QtWidgets.QPushButton(self.widget_price)
        self.button_add.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.button_add.setFont(font)
        self.button_add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_add.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.button_add.setStyleSheet("QPushButton{\n"
"    color:#006EFF;\n"
"    height:30px;\n"
"    padding:0 5px 0 5px;\n"
"    border:1px solid #006EFF;\n"
"    border-radius:8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(216, 216, 216); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: white; \n"
"}")
        self.button_add.setIconSize(QtCore.QSize(20, 20))
        self.button_add.setCheckable(False)
        self.button_add.setChecked(False)
        self.button_add.setAutoExclusive(False)
        self.button_add.setObjectName("button_add")
        self.horizontalLayout.addWidget(self.button_add)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.button_cancel = QtWidgets.QPushButton(self.widget_price)
        self.button_cancel.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.button_cancel.setFont(font)
        self.button_cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_cancel.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.button_cancel.setStyleSheet("QPushButton{\n"
"    color:rgb(255, 53, 53);\n"
"    height:30px;\n"
"    padding:0 5px 0 5px;\n"
"    border:1px solid rgb(255, 53, 53);\n"
"    border-radius:8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(216, 216, 216); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: white; \n"
"}")
        self.button_cancel.setIconSize(QtCore.QSize(20, 20))
        self.button_cancel.setCheckable(False)
        self.button_cancel.setAutoExclusive(False)
        self.button_cancel.setObjectName("button_cancel")
        self.horizontalLayout.addWidget(self.button_cancel)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addWidget(self.widget_price)

        self.retranslateUi(Price)
        QtCore.QMetaObject.connectSlotsByName(Price)

    def retranslateUi(self, Price):
        _translate = QtCore.QCoreApplication.translate
        self.label_stock_quantity.setToolTip(_translate("Price", "Məhsulun anbar qalığı"))
        self.label_stock_quantity.setText(_translate("Price", "Anbar Qalığı:"))
        self.label_quantity.setText(_translate("Price", "Miqdar"))
        self.input_quantity.setToolTip(_translate("Price", "Məhsulun miqdarı"))
        self.input_quantity.setPlaceholderText(_translate("Price", "0"))
        self.label_price.setText(_translate("Price", "Qiymət"))
        self.input_price.setToolTip(_translate("Price", "Məhsulun qiyməti"))
        self.input_price.setPlaceholderText(_translate("Price", "0"))
        self.button_add.setToolTip(_translate("Price", "Enter"))
        self.button_add.setText(_translate("Price", "Təsdiqlə"))
        self.button_add.setShortcut(_translate("Price", "Return"))
        self.button_cancel.setToolTip(_translate("Price", "Esc"))
        self.button_cancel.setText(_translate("Price", "Ləğv et"))
        self.button_cancel.setShortcut(_translate("Price", "Esc"))
import resources_rc
