# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stakeholder.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Stakeholder(object):
    def setupUi(self, Stakeholder):
        Stakeholder.setObjectName("Stakeholder")
        Stakeholder.resize(355, 514)
        Stakeholder.setMinimumSize(QtCore.QSize(355, 0))
        Stakeholder.setMaximumSize(QtCore.QSize(400, 520))
        Stakeholder.setWindowTitle("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/favicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Stakeholder.setWindowIcon(icon)
        Stakeholder.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(Stakeholder)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_stakeholder = QtWidgets.QWidget(Stakeholder)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(False)
        font.setWeight(50)
        self.widget_stakeholder.setFont(font)
        self.widget_stakeholder.setObjectName("widget_stakeholder")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_stakeholder)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_add_stakeholder = QtWidgets.QLabel(self.widget_stakeholder)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_add_stakeholder.setFont(font)
        self.label_add_stakeholder.setStyleSheet("background-color:transparent;")
        self.label_add_stakeholder.setText("")
        self.label_add_stakeholder.setObjectName("label_add_stakeholder")
        self.verticalLayout_6.addWidget(self.label_add_stakeholder)
        self.label_stakeholder_id = QtWidgets.QLabel(self.widget_stakeholder)
        self.label_stakeholder_id.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(3)
        font.setBold(False)
        font.setWeight(50)
        self.label_stakeholder_id.setFont(font)
        self.label_stakeholder_id.setStyleSheet("color:transparent;")
        self.label_stakeholder_id.setText("")
        self.label_stakeholder_id.setObjectName("label_stakeholder_id")
        self.verticalLayout_6.addWidget(self.label_stakeholder_id)
        self.line = QtWidgets.QFrame(self.widget_stakeholder)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_name = QtWidgets.QLabel(self.widget_stakeholder)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_name.setFont(font)
        self.label_name.setStyleSheet("background-color:transparent;")
        self.label_name.setObjectName("label_name")
        self.verticalLayout.addWidget(self.label_name)
        self.input_name = QtWidgets.QLineEdit(self.widget_stakeholder)
        self.input_name.setMinimumSize(QtCore.QSize(200, 0))
        self.input_name.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.input_name.setFont(font)
        self.input_name.setStyleSheet("border:1px solid #006EFF;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:6px;\n"
"height:25px\n"
"")
        self.input_name.setMaxLength(60)
        self.input_name.setPlaceholderText("")
        self.input_name.setClearButtonEnabled(True)
        self.input_name.setObjectName("input_name")
        self.verticalLayout.addWidget(self.input_name)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_type_stakeholder = QtWidgets.QLabel(self.widget_stakeholder)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_type_stakeholder.setFont(font)
        self.label_type_stakeholder.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_type_stakeholder.setStyleSheet("background-color:transparent;")
        self.label_type_stakeholder.setObjectName("label_type_stakeholder")
        self.verticalLayout_8.addWidget(self.label_type_stakeholder)
        self.combobox_type_stakeholder = QtWidgets.QComboBox(self.widget_stakeholder)
        self.combobox_type_stakeholder.setMinimumSize(QtCore.QSize(0, 0))
        self.combobox_type_stakeholder.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.combobox_type_stakeholder.setFont(font)
        self.combobox_type_stakeholder.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.combobox_type_stakeholder.setFocusPolicy(QtCore.Qt.NoFocus)
        self.combobox_type_stakeholder.setStyleSheet("QComboBox {\n"
"    border:1px solid #006EFF;\n"
"    border-radius:2px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    height:26px;\n"
"    width:80px;\n"
"    color:black;\n"
"}\n"
"\n"
"")
        self.combobox_type_stakeholder.setPlaceholderText("")
        self.combobox_type_stakeholder.setDuplicatesEnabled(False)
        self.combobox_type_stakeholder.setFrame(True)
        self.combobox_type_stakeholder.setObjectName("combobox_type_stakeholder")
        self.combobox_type_stakeholder.addItem("")
        self.combobox_type_stakeholder.addItem("")
        self.verticalLayout_8.addWidget(self.combobox_type_stakeholder)
        self.verticalLayout_6.addLayout(self.verticalLayout_8)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_phone = QtWidgets.QLabel(self.widget_stakeholder)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_phone.setFont(font)
        self.label_phone.setToolTip("")
        self.label_phone.setStyleSheet("background-color:transparent;")
        self.label_phone.setObjectName("label_phone")
        self.verticalLayout_3.addWidget(self.label_phone)
        self.input_phone = QtWidgets.QLineEdit(self.widget_stakeholder)
        self.input_phone.setMinimumSize(QtCore.QSize(200, 0))
        self.input_phone.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.input_phone.setFont(font)
        self.input_phone.setStyleSheet("border:1px solid #006EFF;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:6px;\n"
"height:25px\n"
"")
        self.input_phone.setMaxLength(12)
        self.input_phone.setPlaceholderText("")
        self.input_phone.setClearButtonEnabled(True)
        self.input_phone.setObjectName("input_phone")
        self.verticalLayout_3.addWidget(self.input_phone)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_address = QtWidgets.QLabel(self.widget_stakeholder)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_address.setFont(font)
        self.label_address.setToolTip("")
        self.label_address.setStyleSheet("background-color:transparent;")
        self.label_address.setObjectName("label_address")
        self.verticalLayout_5.addWidget(self.label_address)
        self.input_address = QtWidgets.QLineEdit(self.widget_stakeholder)
        self.input_address.setMinimumSize(QtCore.QSize(200, 0))
        self.input_address.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.input_address.setFont(font)
        self.input_address.setStyleSheet("border:1px solid #006EFF;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:6px;\n"
"height:25px\n"
"")
        self.input_address.setMaxLength(55)
        self.input_address.setPlaceholderText("")
        self.input_address.setClearButtonEnabled(True)
        self.input_address.setObjectName("input_address")
        self.verticalLayout_5.addWidget(self.input_address)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_note = QtWidgets.QLabel(self.widget_stakeholder)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_note.setFont(font)
        self.label_note.setStyleSheet("background-color:transparent;")
        self.label_note.setObjectName("label_note")
        self.verticalLayout_4.addWidget(self.label_note)
        self.input_note = QtWidgets.QLineEdit(self.widget_stakeholder)
        self.input_note.setMinimumSize(QtCore.QSize(200, 0))
        self.input_note.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.input_note.setFont(font)
        self.input_note.setStyleSheet("border:1px solid #006EFF;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:6px;\n"
"height:25px\n"
"")
        self.input_note.setText("")
        self.input_note.setMaxLength(55)
        self.input_note.setPlaceholderText("")
        self.input_note.setClearButtonEnabled(True)
        self.input_note.setObjectName("input_note")
        self.verticalLayout_4.addWidget(self.input_note)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_add = QtWidgets.QPushButton(self.widget_stakeholder)
        self.button_add.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.button_add.setFont(font)
        self.button_add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_add.setStyleSheet("QPushButton{\n"
"    color:#006EFF;\n"
"    height:30px;\n"
"    padding:0 5px 0 5px;\n"
"    border:1px solid #006EFF;\n"
"    border-radius:8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(216, 216, 216); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: white; \n"
"}")
        self.button_add.setIconSize(QtCore.QSize(20, 20))
        self.button_add.setCheckable(False)
        self.button_add.setAutoExclusive(False)
        self.button_add.setObjectName("button_add")
        self.horizontalLayout.addWidget(self.button_add)
        self.button_cancel = QtWidgets.QPushButton(self.widget_stakeholder)
        self.button_cancel.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.button_cancel.setFont(font)
        self.button_cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_cancel.setStyleSheet("QPushButton{\n"
"    color:rgb(255, 53, 53);\n"
"    height:30px;\n"
"    padding:0 5px 0 5px;\n"
"    border:1px solid rgb(255, 53, 53);\n"
"    border-radius:8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(216, 216, 216); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: white; \n"
"}")
        self.button_cancel.setIconSize(QtCore.QSize(20, 20))
        self.button_cancel.setCheckable(False)
        self.button_cancel.setAutoExclusive(False)
        self.button_cancel.setObjectName("button_cancel")
        self.horizontalLayout.addWidget(self.button_cancel)
        spacerItem5 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.button_delete = QtWidgets.QPushButton(self.widget_stakeholder)
        self.button_delete.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.button_delete.setFont(font)
        self.button_delete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_delete.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_delete.setStyleSheet("QPushButton{\n"
"    color:rgb(255, 53, 53);\n"
"    height:30px;\n"
"    padding:0 5px 0 5px;\n"
"    border:1px solid rgb(255, 53, 53);\n"
"    border-radius:8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(216, 216, 216); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: white; \n"
"}")
        self.button_delete.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_delete.setIcon(icon1)
        self.button_delete.setIconSize(QtCore.QSize(20, 20))
        self.button_delete.setCheckable(False)
        self.button_delete.setAutoExclusive(False)
        self.button_delete.setObjectName("button_delete")
        self.horizontalLayout.addWidget(self.button_delete)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_7.addWidget(self.widget_stakeholder)

        self.retranslateUi(Stakeholder)
        QtCore.QMetaObject.connectSlotsByName(Stakeholder)

    def retranslateUi(self, Stakeholder):
        _translate = QtCore.QCoreApplication.translate
        self.label_name.setText(_translate("Stakeholder", "Ad - Soyad*"))
        self.input_name.setToolTip(_translate("Stakeholder", "Kontragent adı və soyadı - Bu sahə vacibdir"))
        self.label_type_stakeholder.setText(_translate("Stakeholder", "Kontragent növü"))
        self.combobox_type_stakeholder.setToolTip(_translate("Stakeholder", "Kontragent növü- Bu sahə vacibdir"))
        self.combobox_type_stakeholder.setCurrentText(_translate("Stakeholder", "Tədarükçü"))
        self.combobox_type_stakeholder.setItemText(0, _translate("Stakeholder", "Tədarükçü"))
        self.combobox_type_stakeholder.setItemText(1, _translate("Stakeholder", "Müştəri", "dsffsd"))
        self.label_phone.setText(_translate("Stakeholder", "Telefon*"))
        self.input_phone.setToolTip(_translate("Stakeholder", "Telefon nömrəsi - Bu sahə vacibdir"))
        self.label_address.setText(_translate("Stakeholder", "Ünvan*"))
        self.input_address.setToolTip(_translate("Stakeholder", "Ünvan - Bu sahə vacibdir"))
        self.label_note.setText(_translate("Stakeholder", "Qeyd"))
        self.input_note.setToolTip(_translate("Stakeholder", "Əlavə qeyd"))
        self.button_add.setToolTip(_translate("Stakeholder", "Enter"))
        self.button_add.setText(_translate("Stakeholder", "Təsdiqlə"))
        self.button_add.setShortcut(_translate("Stakeholder", "Return"))
        self.button_cancel.setToolTip(_translate("Stakeholder", "Esc"))
        self.button_cancel.setText(_translate("Stakeholder", "Ləğv et"))
        self.button_cancel.setShortcut(_translate("Stakeholder", "Esc"))
        self.button_delete.setToolTip(_translate("Stakeholder", "Sil - Ctrl+Del"))
        self.button_delete.setShortcut(_translate("Stakeholder", "Ctrl+Del"))
import resources_rc
